# Generated by Django 4.0.4 on 2022-05-26 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('regapp', '0002_profile_user_alter_profile_studentname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='studentname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='studentplace',
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_er',
            field=models.ManyToManyField(blank=True, related_name='follow_er', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow_ing',
            field=models.ManyToManyField(blank=True, related_name='follow_ing', to=settings.AUTH_USER_MODEL),
        ),
    ]
